package com.aisi.dao;

import java.util.List;

import com.aisi.pojo.Product;

public interface ProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Sun Feb 19 14:10:57 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Sun Feb 19 14:10:57 CST 2017
	 */
	int insert(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Sun Feb 19 14:10:57 CST 2017
	 */
	int insertSelective(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Sun Feb 19 14:10:57 CST 2017
	 */
	Product selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Sun Feb 19 14:10:57 CST 2017
	 */
	int updateByPrimaryKeySelective(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Sun Feb 19 14:10:57 CST 2017
	 */
	int updateByPrimaryKey(Product record);
	
	
	
	List<Product> list();
	
	Product selectByName(String name);
	
	
}