package com.aisi.pojo;

public class ProductPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price.id
     *
     * @mbggenerated Sun Feb 19 20:22:23 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price.product_id
     *
     * @mbggenerated Sun Feb 19 20:22:23 CST 2017
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price.group_id
     *
     * @mbggenerated Sun Feb 19 20:22:23 CST 2017
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_price.price
     *
     * @mbggenerated Sun Feb 19 20:22:23 CST 2017
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price
     *
     * @mbggenerated Sun Feb 19 20:22:23 CST 2017
     */
    public ProductPrice(Integer id, Integer productId, Integer groupId, Double price) {
        this.id = id;
        this.productId = productId;
        this.groupId = groupId;
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_price
     *
     * @mbggenerated Sun Feb 19 20:22:23 CST 2017
     */
    public ProductPrice() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price.id
     *
     * @return the value of product_price.id
     *
     * @mbggenerated Sun Feb 19 20:22:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price.id
     *
     * @param id the value for product_price.id
     *
     * @mbggenerated Sun Feb 19 20:22:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price.product_id
     *
     * @return the value of product_price.product_id
     *
     * @mbggenerated Sun Feb 19 20:22:23 CST 2017
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price.product_id
     *
     * @param productId the value for product_price.product_id
     *
     * @mbggenerated Sun Feb 19 20:22:23 CST 2017
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price.group_id
     *
     * @return the value of product_price.group_id
     *
     * @mbggenerated Sun Feb 19 20:22:23 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price.group_id
     *
     * @param groupId the value for product_price.group_id
     *
     * @mbggenerated Sun Feb 19 20:22:23 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_price.price
     *
     * @return the value of product_price.price
     *
     * @mbggenerated Sun Feb 19 20:22:23 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_price.price
     *
     * @param price the value for product_price.price
     *
     * @mbggenerated Sun Feb 19 20:22:23 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}