package com.aisi.pojo;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.id
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.name
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.type_id
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	private Integer typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.price
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.stock
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	private Integer stock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.status
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	private Short status;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	public Product(Integer id, String name, Integer typeId, Double price, Integer stock, Short status) {
		this.id = id;
		this.name = name;
		this.typeId = typeId;
		this.price = price;
		this.stock = stock;
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	public Product() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.id
	 * @return  the value of product.id
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.id
	 * @param id  the value for product.id
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.name
	 * @return  the value of product.name
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.name
	 * @param name  the value for product.name
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.type_id
	 * @return  the value of product.type_id
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.type_id
	 * @param typeId  the value for product.type_id
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.price
	 * @return  the value of product.price
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.price
	 * @param price  the value for product.price
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.stock
	 * @return  the value of product.stock
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	public Integer getStock() {
		return stock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.stock
	 * @param stock  the value for product.stock
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	public void setStock(Integer stock) {
		this.stock = stock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.status
	 * @return  the value of product.status
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.status
	 * @param status  the value for product.status
	 * @mbggenerated  Sat Feb 18 16:56:54 CST 2017
	 */
	public void setStatus(Short status) {
		this.status = status;
	}
}